import { Post, Comment, User, Community } from './types';
import { hashPassword } from './auth';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'TechGuru',
    email: 'techguru@example.com',
    avatar: '👨‍💻',
    karma: 15420,
    role: 'user',
    createdAt: Date.now() - 86400000 * 365,
    bio: 'Full-stack developer and tech enthusiast',
    passwordHash: hashPassword('password123'),
    isBanned: false,
  },
  {
    id: '2',
    username: 'DesignNinja',
    email: 'designninja@example.com',
    avatar: '🎨',
    karma: 8932,
    role: 'user',
    createdAt: Date.now() - 86400000 * 200,
    bio: 'UI/UX designer passionate about beautiful interfaces',
    passwordHash: hashPassword('password123'),
    isBanned: false,
  },
  {
    id: '3',
    username: 'CodeMaster',
    email: 'codemaster@example.com',
    avatar: '⚙️',
    karma: 12500,
    role: 'moderator',
    createdAt: Date.now() - 86400000 * 300,
    bio: 'Senior developer and community moderator',
    passwordHash: hashPassword('password123'),
    isBanned: false,
  },
  {
    id: '4',
    username: 'WebWizard',
    email: 'webwizard@example.com',
    avatar: '🧙',
    karma: 9876,
    role: 'user',
    createdAt: Date.now() - 86400000 * 150,
    bio: 'Web development expert',
    passwordHash: hashPassword('password123'),
    isBanned: false,
  },
  {
    id: '5',
    username: 'Admin',
    email: 'admin@example.com',
    avatar: '👑',
    karma: 50000,
    role: 'admin',
    createdAt: Date.now() - 86400000 * 500,
    bio: 'Platform administrator',
    passwordHash: hashPassword('admin123'),
    isBanned: false,
  },
];

export const mockCommunities: Community[] = [
  {
    id: '1',
    name: 'r/webdev',
    description: 'Web Development Community - Share your projects, ask questions, and discuss web development',
    members: 542000,
    icon: '🌐',
    createdAt: Date.now() - 86400000 * 1000,
    createdBy: '1',
    rules: ['Be respectful', 'No spam', 'Share quality content'],
  },
  {
    id: '2',
    name: 'r/reactjs',
    description: 'React JavaScript Library - Discuss React, hooks, and modern JavaScript',
    members: 389000,
    icon: '⚛️',
    createdAt: Date.now() - 86400000 * 900,
    createdBy: '1',
    rules: ['Stay on topic', 'No self-promotion', 'Help others'],
  },
  {
    id: '3',
    name: 'r/nextjs',
    description: 'Next.js Framework - Share Next.js tips, tricks, and projects',
    members: 156000,
    icon: '▲',
    createdAt: Date.now() - 86400000 * 800,
    createdBy: '1',
    rules: ['Share knowledge', 'Ask questions', 'Be helpful'],
  },
  {
    id: '4',
    name: 'r/design',
    description: 'UI/UX Design - Discuss design principles, tools, and inspiration',
    members: 287000,
    icon: '🎨',
    createdAt: Date.now() - 86400000 * 700,
    createdBy: '2',
    rules: ['Constructive feedback', 'Credit artists', 'No hate speech'],
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    author: 'DesignNinja',
    authorId: '2',
    content: 'Great explanation! This really helped me understand the concept better.',
    timestamp: Date.now() - 3600000,
    upvotes: 245,
    downvotes: 5,
    postId: '1',
  },
  {
    id: 'c2',
    author: 'CodeMaster',
    authorId: '3',
    content: 'I disagree with the approach. Have you considered using hooks instead?',
    timestamp: Date.now() - 7200000,
    upvotes: 89,
    downvotes: 12,
    postId: '1',
  },
  {
    id: 'c3',
    author: 'WebWizard',
    authorId: '4',
    content: 'This is exactly what I was looking for. Thanks for sharing!',
    timestamp: Date.now() - 10800000,
    upvotes: 156,
    downvotes: 2,
    postId: '1',
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'I built a full-stack AI SaaS in 48 hours - Here\'s what I learned',
    author: 'TechGuru',
    authorId: '1',
    content:
      'Used Next.js 15, OpenAI API, Stripe, and Supabase. The app generates custom workout plans using AI. Got 500 signups in the first week! Full breakdown inside.',
    image: '🖼️',
    timestamp: Date.now() - 86400000,
    upvotes: 8942,
    downvotes: 127,
    commentsCount: 1247,
    community: 'r/nextjs',
  },
  {
    id: '2',
    title: 'Stop using useEffect for data fetching. Here\'s why.',
    author: 'CodeMaster',
    authorId: '3',
    content:
      'React Server Components and the new use() hook change everything. I\'ll show you the modern approach that eliminates race conditions and improves performance by 40%.',
    image: '🖼️',
    timestamp: Date.now() - 172800000,
    upvotes: 12456,
    downvotes: 234,
    commentsCount: 2891,
    community: 'r/reactjs',
  },
  {
    id: '3',
    title: 'My design system got 10K stars on GitHub 🎉',
    author: 'DesignNinja',
    authorId: '2',
    content:
      'After 6 months of work, my open-source design system for React hit 10K stars! Includes 200+ components, dark mode, animations, and full TypeScript support. AMA!',
    image: '🖼️',
    timestamp: Date.now() - 259200000,
    upvotes: 15789,
    downvotes: 89,
    commentsCount: 3456,
    community: 'r/design',
  },
  {
    id: '4',
    title: 'I replaced Redux with Zustand and cut bundle size by 60%',
    author: 'WebWizard',
    authorId: '4',
    content:
      'Migrated our entire production app from Redux to Zustand. The results are incredible: faster load times, simpler code, and happier developers. Here\'s the complete migration guide.',
    image: '🖼️',
    timestamp: Date.now() - 345600000,
    upvotes: 9876,
    downvotes: 156,
    commentsCount: 1834,
    community: 'r/webdev',
  },
  {
    id: '5',
    title: 'Landed my dream job at Google after 200+ applications',
    author: 'TechGuru',
    authorId: '1',
    content:
      'After 8 months of grinding LeetCode, building side projects, and getting rejected 200+ times, I finally got an offer from Google. Here\'s my complete journey and tips for you.',
    image: '🖼️',
    timestamp: Date.now() - 432000000,
    upvotes: 23456,
    downvotes: 178,
    commentsCount: 5678,
    community: 'r/webdev',
  },
];

